// Sample compliments array
const compliments = [
    "you're the leafiest of them all!",
"your photosynthesis skills are unmatched!",
"your roots go deep into the soil of excellence!",
"you're the sunshine in the garden of life!",
"your growth is truly remarkable!",
"every leaf on you is like a masterpiece!",
"your chlorophyll game is strong!",
"you're a botanical beauty!",
"your petals are perfection!",
"your fragrance fills the air with joy!",
"your stem stands tall and proud!",
"you're the plant everyone wants to be friends with!",
"your resilience is inspiring!",
"each leaf is a stroke of nature's paintbrush!",
"your colors are a feast for the eyes!",
"your symmetry is simply stunning!",
"every day with you is a breath of fresh air!",
"your beauty is rooted in simplicity!",
"your presence makes the whole room bloom!",
"your leaves are like green poetry!",
"your branches reach for the stars!",
"your energy is positively radiant!",
"your soil must be made of stardust!",
"you're the green heart of the garden!",
"your presence brings tranquility!",
"your leaves dance in the breeze like a ballet!",
"you're the queen/king of the plant kingdom!",
"your foliage is a work of art!",
"your petals are like delicate whispers of nature!",
"your existence is a botanical blessing!",
"your leaves are a canvas of life!",
"you're the VIP (Very Important Plant)!",
"your roots are like anchors of strength!",
"your blooms are a celebration of life!",
"your greenery is a symbol of hope!",
"your photosynthesis game is on point!",
"your leaves are a symphony of shapes!",
"your fragrance is nature's perfume!",
"your stems are like nature's architecture!",
"your colors are a palette of happiness!",
"your petals are like gentle strokes of a paintbrush!",
"your growth is a testament to your strength!",
"your leaves shimmer like emeralds!",
"your presence is a natural stress-buster!",
"your roots are the foundation of life!",
"your foliage is a living masterpiece!",
"your blooms are a testament to your vitality!",
"your branches are like arms reaching out for a hug!",
"your chloroplasts must be working overtime!",
"your greenery is a source of endless joy!",
"your beauty is as perennial as your leaves!",
"your roots run deep, anchoring you in grace!",
"your leaves are a celebration of life's greenery!",
"your fragrance is a breath of pure bliss!",
"your stems stand tall with botanical pride!",
"your petals are like poetry in motion!",
"your leaves are the envy of every garden!",
"your presence is a natural mood lifter!",
"your growth is a journey of beauty!",
"your roots are the unsung heroes of nature!",
"your foliage is a testament to your vitality!",
"your petals are like delicate whispers in the wind!",
"your branches are like the arms of nature embracing life!",
"your chlorophyll is a superhero in disguise!",
"your leaves are like a green carpet of splendor!",
"your fragrance is a sweet melody in the air!",
"your stems are like pillars of botanical strength!",
"your colors are a visual feast for the eyes!",
"your petals are like gentle caresses of nature!",
"your growth is an ode to life's resilience!",
"your roots are the foundation of your natural beauty!",
"your leaves are the epitome of green elegance!",
"your presence is a symphony of nature's harmony!",
"your blooms are a testament to the magic of life!",
"your branches are like the arms of nature embracing the world!",
"your chlorophyll is the unsung hero in the tale of photosynthesis!",
"your greenery is a masterpiece in the canvas of nature!",
"your fragrance is a sweet embrace of floral bliss!",
"your stems are like the majestic pillars of a botanical palace!",
"your colors are a kaleidoscope of natural beauty!",
"your petals are delicate whispers of nature's poetry!",
"your growth is a journey of everlasting vitality!",
"your roots are the anchors of your botanical grace!",
"your leaves are like the pages of a green storybook!",
"your presence is a natural remedy for a weary soul!",
"your blooms are a celebration of life's perpetual renewal!",
"your branches are like the bridges connecting the realms of flora!",
"your chlorophyll is the magical potion fueling the elixir of life!",
"your greenery is the enchanting forest in the kingdom of existence!",
"your fragrance is the subtle perfume lingering in the air of serenity!",
"your stems are like the proud columns supporting the palace of flora!",
"your colors are the vibrant strokes on the canvas of existence!",
"your petals are the delicate dancers in the ballroom of nature!",
"your growth is the eternal dance in the ballroom of botanical beauty!",
"your roots are the wise elders in the village of the garden!",
"your leaves are the green poems written by the hand of life!",
"your presence is the soothing melody in the symphony of existence!",
"your blooms are the radiant stars in the celestial dance of nature!",
"your branches are the bridges connecting the realms of flora!",
"your chlorophyll is the magical potion fueling the elixir of life!",
"your greenery is the enchanting forest in the kingdom of existence!",
"your fragrance is the subtle perfume lingering in the air of serenity!",
"your stems are like the proud columns supporting the palace of flora!",
"your colors are the vibrant strokes on the canvas of existence!",
"your petals are the delicate dancers in the ballroom of nature!",
"your growth is the eternal dance in the ballroom of botanical beauty!",
"your roots are the wise elders in the village of the garden!",
"your leaves are the green poems written by the hand of life!",
"your presence is the soothing melody in the symphony of existence!",
"your blooms are the radiant stars in the celestial dance of nature!",
"your branches are the bridges connecting the realms of flora!",
"your chlorophyll is the magical potion fueling the elixir of life!",
"your greenery is the enchanting forest in the kingdom of existence!",
"your fragrance is the subtle perfume lingering in the air of serenity!",
"your stems are like the proud columns supporting the palace of flora!",
"your colors are the vibrant strokes on the canvas of existence!",
"your petals are the delicate dancers in the ballroom of nature!",
"your growth is the eternal dance in the ballroom of botanical beauty!",
"your roots are the wise elders in the village of the garden!",
"your leaves are the green poems written by the hand of life!",
"your presence is the soothing melody in the symphony of existence!",
"your blooms are the radiant stars in the celestial dance of nature!",
"your branches are the bridges connecting the realms of flora!",
"your chlorophyll is the magical potion fueling the elixir of life!",
"your greenery is the enchanting forest in the kingdom of existence!",
"your fragrance is the subtle perfume lingering in the air of serenity!",
"your stems are like the proud columns supporting the palace of flora!",
"your colors are the vibrant strokes on the canvas of existence!",
"your petals are the delicate dancers in the ballroom of nature!",
"your growth is the eternal dance in the ballroom of botanical beauty!",
"your roots are the wise elders in the village of the garden!",
"your leaves are the green poems written by the hand of life!",
"your presence is the soothing melody in the symphony of existence!",
"your blooms are the radiant stars in the celestial dance of nature!",
"your branches are the bridges connecting the realms of flora!",
"your chlorophyll is the magical potion fueling the elixir of life!",
"your greenery is the enchanting forest in the kingdom of existence!",
"your fragrance is the subtle perfume lingering in the air of serenity!",
"your stems are like the proud columns supporting the palace of flora!",
"your colors are the vibrant strokes on the canvas of existence!",
"your petals are the delicate dancers in the ballroom of nature!",
"your growth is the eternal dance in the ballroom of botanical beauty!",
"your roots are the wise elders in the village of the garden!",
"your leaves are the green poems written by the hand of life!",
"your presence is the soothing melody in the symphony of existence!",
"your blooms are the radiant stars in the celestial dance of nature!",
"your branches are the bridges connecting the realms of flora!",
"your chlorophyll is the magical potion fueling the elixir of life!",
"your greenery is the enchanting forest in the kingdom of existence!",
"your fragrance is the subtle perfume lingering in the air of serenity!",
"your stems are like the proud columns supporting the palace of flora!",
"your colors are the vibrant strokes on the canvas of existence!",
"your petals are the delicate dancers in the ballroom of nature!",
"your growth is the eternal dance in the ballroom of botanical beauty!",
"your roots are the wise elders in the village of the garden!",
"your leaves are the green poems written by the hand of life!",
"your presence is the soothing melody in the symphony of existence!",
"your blooms are the radiant stars in the celestial dance of nature!",
"your branches are the bridges connecting the realms of flora!",
"your chlorophyll is the magical potion fueling the elixir of life!",
"your greenery is the enchanting forest in the kingdom of existence!",
"your fragrance is the subtle perfume lingering in the air of serenity!",
"your stems are like the proud columns supporting the palace of flora!",
"your colors are the vibrant strokes on the canvas of existence!",
"your petals are the delicate dancers in the ballroom of nature!",
"your growth is the eternal dance in the ballroom of botanical beauty!",
"your roots are the wise elders in the village of the garden!",
"your leaves are the green poems written by the hand of life!",
"your presence is the soothing melody in the symphony of existence!",
"your blooms are the radiant stars in the celestial dance of nature!",
"your branches are the bridges connecting the realms of flora!",
"your chlorophyll is the magical potion fueling the elixir of life!",
"your greenery is the enchanting forest in the kingdom of existence!",
"your fragrance is the subtle perfume lingering in the air of serenity!",
"your stems are like the proud columns supporting the palace of flora!",
"your colors are the vibrant strokes on the canvas of existence!",
"your petals are the delicate dancers in the ballroom of nature!",
"your growth is the eternal dance in the ballroom of botanical beauty!",
"your roots are the wise elders in the village of the garden!",
"your leaves are the green poems written by the hand of life!",
"your presence is the soothing melody in the symphony of existence!",
"your blooms are the radiant stars in the celestial dance of nature!",
"your branches are the bridges connecting the realms of flora!",
"your chlorophyll is the magical potion fueling the elixir of life!",
"your greenery is the enchanting forest in the kingdom of existence!",
"your fragrance is the subtle perfume lingering in the air of serenity!",
"your stems are like the proud columns supporting the palace of flora!",
"your colors are the vibrant strokes on the canvas of existence!",
"your petals are the delicate dancers in the ballroom of nature!",
"your growth is the eternal dance in the ballroom of botanical beauty!",
"your roots are the wise elders in the village of the garden!",
"your leaves are the green poems written by the hand of life!",
"your presence is the soothing melody in the symphony of existence!",
"your blooms are the radiant stars in the celestial dance of nature!",
"your branches are the bridges connecting the realms of flora!",
"your chlorophyll is the magical potion fueling the elixir of life!",
"your greenery is the enchanting forest in the kingdom of existence!",
"your fragrance is the subtle perfume lingering in the air of serenity!",
"your stems are like the proud columns supporting the palace of flora!",
"your colors are the vibrant strokes on the canvas of existence!",
"your petals are the delicate dancers in the ballroom of nature!",
"your growth is the eternal dance in the ballroom of botanical beauty!",
"your roots are the wise elders in the village of the garden!",
"your leaves are the green poems written by the hand of life!",
"your presence is the soothing melody in the symphony of existence!",
"your blooms are the radiant stars in the celestial dance of nature!",
"your branches are the bridges connecting the realms of flora!",
"your chlorophyll is the magical potion fueling the elixir of life!",
"your greenery is the enchanting forest in the kingdom of existence!",
"your fragrance is the subtle perfume lingering in the air of serenity!",
"your stems are like the proud columns supporting the palace of flora!",
"your colors are the vibrant strokes on the canvas of existence!",
"your petals are the delicate dancers in the ballroom of nature!",
"your growth is the eternal dance in the ballroom of botanical beauty!",
"your roots are the wise elders in the village of the garden!",
"your leaves are the green poems written by the hand of life!",
"your presence is the soothing melody in the symphony of existence!",
"your blooms are the radiant stars in the celestial dance of nature!",
"your branches are the bridges connecting the realms of flora!",
"your chlorophyll is the magical potion fueling the elixir of life!",
"your greenery is the enchanting forest in the kingdom of existence!",
"your fragrance is the subtle perfume lingering in the air of serenity!",
"your stems are like the proud columns supporting the palace of flora!",
"your colors are the vibrant strokes on the canvas of existence!",
"your petals are the delicate dancers in the ballroom of nature!",
"your growth is the eternal dance in the ballroom of botanical beauty!",
"your roots are the wise elders in the village of the garden!",
"your leaves are the green poems written by the hand of life!",
"your presence is the soothing melody in the symphony of existence!",
"your blooms are the radiant stars in the celestial dance of nature!",
"your branches are the bridges connecting the realms of flora!",
"your chlorophyll is the magical potion fueling the elixir of life!",
"your greenery is the enchanting forest in the kingdom of existence!",
"your fragrance is the subtle perfume lingering in the air of serenity!",
"your stems are like the proud columns supporting the palace of flora!",
"your colors are the vibrant strokes on the canvas of existence!",
"your petals are the delicate dancers in the ballroom of nature!",
"your growth is the eternal dance in the ballroom of botanical beauty!",

"your roots are the wise elders in the village of the garden!",
"your leaves are a work of art!",
"photosynthesis? you nail it every time!",
"you're the sunshine of my garden!",
"your stems are as strong as your spirit!",
"every petal is a masterpiece.",
"your fragrance is the envy of other plants.",
"you make the soil proud!",
"i bet the other plants are jealous of your beauty!",
"your chlorophyll game is on point!",
"growth looks good on you!",
"your roots are as deep as your wisdom.",
"you're the VIP (Very Important Plant) in my garden.",
"in a world of plants, you're the rare bloom!",
"your petals are poetry in motion.",
"you're the green thumb's dream!",
"flourishing and fabulous, that's you!",
"if plants had oscars, you'd be the winner!",
"you're a photosynthesis prodigy!",
"your leaves are like a green symphony.",
"a garden without you is just a patch of land.",
"your presence makes the whole garden shine.",
"you're the trendsetter in the plant world.",
"the bees would rate your nectar 10/10.",
"your beauty outshines even the brightest flowers.",
"you're the plant version of a rockstar!",
"your roots run deep, just like your impact.",
"your resilience is an inspiration to all plants.",
"you're the reigning monarch of the garden.",
"other plants wish they could photosynthesize like you.",
"you're the reason my garden is a paradise.",
"your petals are softer than a morning breeze.",
"even the rain wants to touch your leaves.",
"your chloroplasts deserve a standing ovation!",
"you're the crown jewel of my botanical collection.",
"the earth smiles when you bloom.",
"you're the shakespeare of the plant kingdom.",
"your roots are firmly grounded in awesomeness.",
"your beauty is a beacon for butterflies.",
"you're the green goddess of growth.",
"you turn sunlight into pure magic!",
"your fragrance is like a symphony for the senses.",
"you're the Michaelangelo of the plant world.",
"every leaf is a stroke of genius.",
"your petals are poetry written in chlorophyll.",
"you're the VIP (Very Important Plant) in my garden.",
"your colors are a feast for the eyes.",
"your presence makes the garden come alive.",
"you're the trendsetter among the tulips.",
"the bees write poems about your nectar.",
"your beauty outshines even the sunflowers.",
"you're the plant version of a pop sensation!",
"your roots run deep, just like your significance.",
"your resilience is an inspiration to all blooms.",
"you're the reigning monarch of the flowerbed.",
"other plants dream of photosynthesizing like you.",
"you're the reason my garden is a haven.",
"your petals are softer than a morning drizzle.",
"even the rain wants to dance on your leaves.",
"your chloroplasts deserve a garden full of applause!",
"you're the crown jewel of my horticultural treasures.",
"the earth applauds when you bloom.",
"you're the shakespeare of the horticultural realm.",
"your roots are firmly anchored in magnificence.",
"your beauty is a beacon for butterflies and bees.",
"you're the green goddess of gardening.",
"you turn sunlight into sheer enchantment!",
"your fragrance is a symphony for the olfactory senses.",
"you're the michelangelo of the flora world.",
"every leaf is a stroke of genius and a touch of elegance.",
"your petals are poetry written with a green quill.",
"you're the VIP (Very Important Plant) in my backyard.",
"your colors are a visual feast and a delight for the eyes.",
"your presence makes the entire garden come alive.",
"you're the trendsetter among the tulips and roses.",
"the bees compose sonnets about the sweetness of your nectar.",
"your beauty outshines even the brightest sunflowers.",
"you're the plant version of a sensational superstar!",
"your roots run deep, just like your everlasting impact.",
"your resilience is an inspiration to all flora.",
"you're the reigning monarch of the botanical realm.",
"other plants fantasize about photosynthesizing like you.",
"you're the reason my garden is a sanctuary of joy.",
"your petals are softer than a gentle morning breeze.",
"even the rain yearns to tap dance on your exquisite leaves.",
"your chloroplasts deserve a grand gala of applause!",
"you're the crown jewel of my verdant collection.",
"the earth celebrates when you unfurl your blossoms.",
"you're the shakespeare of the plant kingdom, with leaves as your verses.",
"your roots are firmly grounded in magnificence and grandeur.",
"your beauty is a beacon for butterflies, bees, and humans alike.",
"you turn sunlight into sheer enchantment, painting the garden with your brilliance.",
"your fragrance is a symphony for the olfactory senses, a melody of floral delight.",
"you're the michelangelo of the flora world, sculpting elegance from every petal.",
"every leaf is a stroke of genius and a touch of elegance, a masterpiece in chlorophyll.",
"your petals are poetry written with a green quill, a sonnet of nature's creativity.",
"you're the VIP (Very Important Plant) in my backyard, a star in the botanical cosmos.",
"your colors are a visual feast and a delight for the eyes, a palette of horticultural splendor.",
"your presence makes the entire garden come alive, a vibrant tapestry of life.",
"you're the trendsetter among the tulips and roses, a fashion icon in the botanical world.",
"the bees compose sonnets about the sweetness of your nectar, a love story in every bloom."
];

function generateCompliment() {
    // Get the input value
    const plantName = document.getElementById('plantName').value;

    // If the user entered a plant name
    if (plantName.trim() !== '') {
        // Randomly select a compliment
        const randomCompliment = compliments[Math.floor(Math.random() * compliments.length)];

        // Display the compliment
        const resultElement = document.getElementById('complimentResult');
        resultElement.textContent = `${plantName}, ${randomCompliment}`;
    } else {
        alert("Please enter your plant's name!");
    }
}
